
# ----> WHEN THE DEVELOPMENT STAGE WAS FINISHED TRANSFER THE VARIABLE TO _config.yml
#THS IS THE PRINCIPAL FILE ON DIRETORY, IT WILL RUN YOUR SITE, WIHOUT THAT THE SITE
# WILL SHOW ERROR.

title: raincorn
lead: We are work to make the purposes on the web.
ministry: Alipseight
maintained: Core team
email: avorent@gmail.com
url: "https://avorent.github.io"
repo: "https://github.com/avorent/avorent.github.io"

# SITE CONFIG

currently_version: 0.0.0
currently_release: 0.0.0
currently_stage: beta
markdown: kramdown
