
# FILE TO RUN THIS SITE IN LOCAL SERVER

title: raincorn
lead: We are work to make the purposes on the web.
ministry: Alipseight
maintained: Core team
email: avorent@gmail.com
url: "https://avorent.github.io"
repo: "https://github.com/avorent/avorent.github.io"

# SITE CONFIG

currently_version: 2.0.1
currently_release: 2.0.1-rls
currently_stage: beta
markdown: kramdown
